### ISSUE TITLE
Can't change language in CLI

### ISSUE THREAD

**Issue by gbelvedere** [divhide/node-subtitler#28]
when using: 

`subtitler name_of_file.mp4 -lang spa`

It is always downloading the english version, I've tried with several languages, and nothing happens. 

Even when using with the -n option it downloads the 5 files, but all in english.

**Comment by aetheon** [comment]
Hi @gbelvedere have you tried:
`subtitler name_of_file.mp4 --lang spa`
or 
`LANG=spa subtitler name_of_file.mp4`

**Comment by chatch** [comment]
@gbelvedere use "--lang" rather then "-lang". The examples show "-lang" but it doesn't work.

**Comment by aetheon** [comment]
PR was merged, closing this. tks
