### ISSUE TITLE
Incorrect header check

### ISSUE THREAD

**Issue by Danielv123** [divhide/node-subtitler#36]
I believe something changed in the headers from opensubtitles recently as all my installs of this tool has stopped working.

```
Download         http://dl.opensubtitles.org/en/download/src-api/vrf-19d20c5d/sid-XiRUg0k,MOXhrH54j3gkQ322qC5/filead/1954645909.gz
------------------------
...Downloading
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Gunzip.zlibOnError (zlib.js:153:15)
```

The trace isn't particularily helpful and I have no idea where to start looking for the problem.

**Comment by abewartech** [comment]
![image](https://user-images.githubusercontent.com/29395602/120890188-37faaa80-c62b-11eb-8bc6-af88e5342929.png)

**Comment by abewartech** [comment]
I think this limit from opensubtitle

Solved with VPN
